config/routes.rb
Stupro::Application.routes.draw do
  root :to => "home#index"
  get "home/index"

  resources :donations

  resources :donors

  resources :students

end

app/models/donation.rb
class Donation < ActiveRecord::Base
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  has_many :donations
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :donations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # GET /donations
  # GET /donations.xml
  def index
    @donations = Donation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @donations }
    end
  end

  # GET /donations/1
  # GET /donations/1.xml
  def show
    @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.xml
  def new
    @donation = Donation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.xml
  def create
    @donation = Donation.new(params[:donation])

    respond_to do |format|
      if @donation.save
        format.html { redirect_to(@donation, :notice => 'Donation was successfully created.') }
        format.xml  { render :xml => @donation, :status => :created, :location => @donation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @donation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.xml
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to(@donation, :notice => 'Donation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @donation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.xml
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to(donations_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  # GET /donors
  # GET /donors.xml
  def index
    @donors = Donor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @donors }
    end
  end

  # GET /donors/1
  # GET /donors/1.xml
  def show
    @donor = Donor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @donor }
    end
  end

  # GET /donors/new
  # GET /donors/new.xml
  def new
    @donor = Donor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @donor }
    end
  end

  # GET /donors/1/edit
  def edit
    @donor = Donor.find(params[:id])
  end

  # POST /donors
  # POST /donors.xml
  def create
    @donor = Donor.new(params[:donor])

    respond_to do |format|
      if @donor.save
        format.html { redirect_to(@donor, :notice => 'Donor was successfully created.') }
        format.xml  { render :xml => @donor, :status => :created, :location => @donor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @donor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /donors/1
  # PUT /donors/1.xml
  def update
    @donor = Donor.find(params[:id])

    respond_to do |format|
      if @donor.update_attributes(params[:donor])
        format.html { redirect_to(@donor, :notice => 'Donor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @donor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.xml
  def destroy
    @donor = Donor.find(params[:id])
    @donor.destroy

    respond_to do |format|
      format.html { redirect_to(donors_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.xml
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @students }
    end
  end

  # GET /students/1
  # GET /students/1.xml
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/new
  # GET /students/new.xml
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.xml
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to(@student, :notice => 'Student was successfully created.') }
        format.xml  { render :xml => @student, :status => :created, :location => @student }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.xml
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to(@student, :notice => 'Student was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.xml
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to(students_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :donor_id %><br />
    <%= f.text_field :donor_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<h1>Listing donations</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Donor</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @donations.each do |donation| %>
  <tr>
    <td><%= donation.student_id %></td>
    <td><%= donation.donor_id %></td>
    <td><%= donation.amount %></td>
    <td><%= link_to 'Show', donation %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
    <td><%= link_to 'Destroy', donation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @donation.student_id %>
</p>

<p>
  <b>Donor:</b>
  <%= @donation.donor_id %>
</p>

<p>
  <b>Amount:</b>
  <%= @donation.amount %>
</p>


<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/donors/_donation_list.html.erb
<h1>Your Donations</h1>

<table>
  <tr>
    <th>Student Id</th>
    <th>Student Name</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% donations.each do |donation| %>
  <tr>
    <td><%= donation.student_id %></td>
    <% @sel_students = Student.find_all_by_id(donation.student_id) %>
    <% for sel_student in @sel_students %>
    <td><%= sel_student.name %></td>
    <% end %>
    <td><%= donation.amount %></td>
    <td><%= link_to 'Show', donation %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
    <td><%= link_to 'Destroy', donation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/donors/_form.html.erb
<%= form_for(@donor) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% @donor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donors/_new_donation.html.erb
<h1>Wanna Donate?</h1>

<%= form_for(donation) do |f| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.text_field :student_id %>
  </div>
    <%= f.hidden_field :donor_id %>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing donor</h1>

<%= render 'form' %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<h1>Listing donors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @donors.each do |donor| %>
  <tr>
    <td><%= donor.name %></td>
    <td><%= donor.username %></td>
    <td><%= donor.city %></td>
    <td><%= link_to 'Show', donor %></td>
    <td><%= link_to 'Edit', edit_donor_path(donor) %></td>
    <td><%= link_to 'Destroy', donor, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Donor', new_donor_path %>

app/views/donors/new.html.erb
<h1>New donor</h1>

<%= render 'form' %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<h1><%= @donor.name %> Details</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @donor.name %>
</p>

<p>
  <b>Username:</b>
  <%= @donor.username %>
</p>

<p>
  <b>City:</b>
  <%= @donor.city %>
</p>

<%= render :partial=>"donation_list", :locals=>{:donations=>@donor.donations} %>

<%= render :partial=>"new_donation", :locals=>{:donation=>Donation.new(:donor_id=>@donor.id)} %>

<%= link_to 'Edit', edit_donor_path(@donor) %> |
<%= link_to 'Back', donors_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Student Donor and Donations</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<h1>Welcome to the Student, Donor and Donations Management System</h1>
<p>This is prototype model for the creation of Student, Donor and Donation database system. You will notice the following functionality:</p>
<ol>
    <li>When a Student is Displayed, the system also lists the Donations and the Donor ID associated with the student</li>
    <li>When a Donor is Displayed, system shows the Donor information as well as his donations and also provides a way for him to Donate more. He just has to put the Student ID while donating for proper linkage</li>
    <li>New donations can be added by the admin or the Donor but none of the donation can be changed by the Student. A student can just view the donation done to him/her</li>
</ol>
<blockquote>Click on each of the Above menu to have a better idea of the whole application. You can also play around this system by adding NEW DATA OR editing OLD DATA</blockquote>
<h3>Hope this serves as a good prototype for the START of the full-fledged model. The whole functionality is done through Ruby on Rails</h3>
<pre>By the way, I am located at /app/views/home/<index class="html erb"></index></pre>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Student Donor and Donations | <%= controller.action_name %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<ul class="green">
    <li><a href="http://evening-earth-128.heroku.com" title="home" class="current"><span>Home</span></a></li>
	<li><a href="http://evening-earth-128.heroku.com/students" title="students"><span>Students</span></a></li>
    <li><a href="http://evening-earth-128.heroku.com/donors" title="donors"><span>Donors</span></a></li>
    <li><a href="http://evening-earth-128.heroku.com/donations" title="donations"><span>All Donations</span></a></li>
    <li><a href="#" title="contact"><span>Contact</span></a></li>
</ul>
<br/><br/><br/>
<%= yield %>

</body>
</html>

app/views/students/_donation_list.html.erb
<h1>Received donations</h1>

<table>
  <tr>
    <th>Donor Id</th>
    <th>Donor Name</th>
    <th>Amount</th>
    <th></th>
  </tr>

<% donations.each do |donation| %>
  <tr>
    <td><%= donation.donor_id %></td>
    <% @sel_donors = Donor.find_all_by_id(donation.donor_id) %>
    <% for sel_donor in @sel_donors %>
    <td><%= sel_donor.name %></td>
    <% end %>
    <td><%= donation.amount %></td>
    <td><%= link_to 'Show', donation %></td>
  </tr>
<% end %>
</table>

<br />

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.age %></td>
    <td><%= student.city %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<h1><%= @student.name %> Details</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Age:</b>
  <%= @student.age %>
</p>

<p>
  <b>City:</b>
  <%= @student.city %>
</p>

<%= render :partial=>"donation_list", :locals=>{:donations=>@student.donations} %>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>